### ISSUE TITLE
i used the onchange event to get values in console but it's not working 

### ISSUE THREAD

**Issue by Umer-khokher** [habibmhamadi/multi-select-tag#12]
new MultiSelectTag('countries', {
    rounded: true,    // default true
    shadow: true,      // default false
    placeholder: 'Search',  // default Search...
    onChange: function(values) {
        console.log(values)
    }
})

**Comment by ARehman-Nets** [comment]
Yes, i was struggling it from hours. So i discovered a way for getting the values:

you need to change js file: src\js\multi-select-tag.js

In JS add an id to arrow down button (On click which gets all the options):

button = document.createElement('button')
button.type = 'button'
button.id = 'btn_id'
btnContainer.append(button)



then create an event to that function and try to get selected options using jquery using function provided below:

function get_multiple_input_values_to_array(id){
                return  $("#"+id+" div.mult-select-tag div.item-label").map(function() {
                    return $(this).text();
                }).get();
            }
            
            
            call the function - pass the form group id to this function it will gives you a list of all selected values.

**Comment by ARehman-Nets** [comment]
> @ARehman-Nets @Umer-khokher Guys the `onChange` function is already there in source code but the problem is with CDN. it still uses the old version of the script even I purged it many times.

Please update CDN files.

**Comment by habibmhamadi** [comment]
@Umer-khokher You can copy the content from `dist/js/`.

**Comment by Umer-khokher** [comment]
i used it like this but nothing comes up in console if you know anything please let me know
[Uploading formultiselectzip.zip…]()

**Comment by habibmhamadi** [comment]
@ARehman-Nets @Umer-khokher Hi I just released version v2.0.0 to fix this issue. now you can use this version from cdn.
`<script src="https://cdn.jsdelivr.net/gh/habibmhamadi/multi-select-tag@2.0.0/dist/js/multi-select-tag.js"></script>`

**Comment by Umer-khokher** [comment]
thanks alot for your support
