### ISSUE TITLE
Remove the search bar

### ISSUE THREAD

**Issue by Skyzel061026** [habibmhamadi/multi-select-tag#15]
is there a way to remove the search input
i try to use this but nothing happen
(function() {
            new MultiSelectTag('skill-level', {
                rounded: true,
                shadow: true,
                search: false,
                tagColor: {
                    textColor: '#000000',
                    borderColor: '#e1e1e1',
                    bgColor: '#e1e1e1',
                }
            });
        })();

**Comment by habibmhamadi** [comment]
No there is no option to remove search input.
