### ISSUE TITLE
How to update the options if the select id is updated from which the Multiselcttag was created?

### ISSUE THREAD

**Issue by sapreparth** [habibmhamadi/multi-select-tag#17]
<select id='job'>
<options value='a'>A</option>
</select>

<script> new MultiSelectTag('job') </script>

Now the select id options changes to : 
<select id='job'>
<options value='a'>A</option>
<options value='b'>B</option>
</select>

how to update the dropdown created by MultiSlelectTag?

**Comment by IcaroRodrigo** [comment]
I managed to make a workaround by selecting or creating other options. After that, just remove the visual customization and recreate it.

`var select = document.getElementById("itens");
    response.itens.forEach(item => {
        for (var i = 0; i < select.options.length; i++) {
            var option = select.options[i];
            if (option.value == item.produtoItem.id)
                option.selected = true;
        }
    });
    listElements = document.getElementsByClassName("mult-select-tag")
    listElements[0].remove();
    new MultiSelectTag('itens');
`

In my case, I needed to select some options, but it can easily be converted to create other elements (options)

**Comment by habibmhamadi** [comment]
@sapreparth Why should the id of an element be changed? I think you need to find a better way to achieve a solution to your problem.
