### ISSUE TITLE
problem having the first value on the list set automatically without being chosen 

### ISSUE THREAD

**Issue by ibrahimslimvk** [habibmhamadi/multi-select-tag#4]
here is my code 

```
<div class="col">
			<div  class="form-group ">
			<?php 
    $query ="SELECT user_name FROM admin_profile where user_role='Designer' or user_role='Checker' ";
    $result = $conn->query($query);
    if($result->num_rows> 0){
      $options= mysqli_fetch_all($result, MYSQLI_ASSOC);
	}
?>
           <label>Designer CA</label>
			<select class="form-control"  name="designer_ca" id="designer_ca" >
			<option disabled value=""  ></option>
  <?php 
  foreach ($options as $option) {
  ?>
	<option value="<?php echo $option['user_name']; ?>"  <?php if (!empty($designer_ca) && $designer_ca == $option['user_name']) echo "selected"; ?>   ><?php echo $option['user_name']; ?> </option>
    <?php 
    }
   ?>
</select>
	</div>
		</div> 
```
![github](https://github.com/habibmhamadi/multi-select-tag/assets/52632297/14a81f02-8f5c-4994-9832-790b01aa3ffa)

as shown in the screenshot "8003" is the first choice on the drop down list but i did not choose it as it was chosen automatically 
can you guide me please what is exactly the issue ?

**Comment by habibmhamadi** [comment]
It is chosen because the following condition `<?php if (!empty($designer_ca) && $designer_ca == $option['user_name']) echo "selected"; ?> `. 
This condition results true.

**Comment by ibrahimslimvk** [comment]
but in add new job case Designer ca in the database still has no data so $designer_ca is already empty which does not result the condition to be true is there a way which i can edit my code to avoid this?
