### ISSUE TITLE
Keep dropdown open for multiple selections

### ISSUE THREAD

**Issue by nathanvick480** [habibmhamadi/multi-select-tag#9]
This is really helpful—thank you very much! 

Is there a way to keep the dropdown open while selecting multiple items, without having to click the button to reopen the dropdown after every selection? That would let users intuitively recognize that they can make multiple selections (otherwise, if they didn't read the instructions, they might think it's only possible to select one item).

**Comment by habibmhamadi** [comment]
@nathanvick480 Hello, there is no such a feature available. And I saw lots of multiple tag selections behave the same.
